[config]
schemaVersion = "1.0.0"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "SWaffles"
name = "SWaffleCon"
description = "A Server and external client for development and debugging."
websiteUrl = "https://github.com/ShastaWaffles/SWaffleConsole" 
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_PEAK = "5.4.2403"

[build]
icon = "../../icon.png"
readme = "../../README.md"
outdir = "../../artifacts/thunderstore/"

[[build.copy]]
source = "../../artifacts/bin/SWaffleCon/release/com.github.Shastafication.SwaffleConsole.dll"
target = "plugins/"

[[build.copy]]
source = "../../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../../LICENSE"
target = "/"

# The following config options only apply when using TCLI to publish to Thunderstore directly:

[publish]
# See communities at:
# https://thunderstore.io/api/experimental/community/
communities = [ "peak", ]

[publish.categories]
# See categories at:
# https://thunderstore.io/api/experimental/community/peak/category/
peak = [ "mods", "tools", ]
